name: raxmlng_support
description: Compute bipartition support for a given reference tree using an existing set of replicate trees
keywords:
  - phylogeny
  - newick
  - maximum likelihood
tools:
  - raxmlng:
      description: 'RAxML Next Generation: faster, easier-to-use and more flexible'
      homepage: https://github.com/amkozlov/raxml-ng
      documentation: https://github.com/amkozlov/raxml-ng/wiki
      tool_dev_url: https://github.com/amkozlov/raxml-ng
      doi: doi.org/10.1093/bioinformatics/btz305
      licence: ["GPL v2-or-later"]

input:
  - tree:
      type: file
      description: Best-scoring tree in Newick format
      pattern: "*.{raxml.bestTree,nwk}"
  - bootstraps:
      type: file
      description: Iteration bootstraps of the phylogenetic tree
      pattern: "*.{raxml.bootstraps,nwk}"

output:
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - bam:
      type: file
      description: Annotated support tree in Newick format
      pattern: "*.{raxml.support}"

authors:
  - "@MillironX"
