name: raxmlng_search
description: Run topology search to find the best-scoring ML tree
keywords:
  - phylogeny
  - newick
  - maximum likelihood
tools:
  - raxmlng:
      description: 'RAxML Next Generation: faster, easier-to-use and more flexible'
      homepage: https://github.com/amkozlov/raxml-ng
      documentation: https://github.com/amkozlov/raxml-ng/wiki
      tool_dev_url: https://github.com/amkozlov/raxml-ng
      doi: doi.org/10.1093/bioinformatics/btz305
      licence: ["GPL v2-or-later"]

input:
  - msa:
      type: file
      description: A FASTA or RAxML format multiple sequence aligment file
      pattern: "*.{fasta,fas,fa,mfa,rba}"

output:
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - best_tree:
      type: file
      description: Best-scoring tree in Newick format
      pattern: "*.{raxml.bestTree}"

authors:
  - "@MillironX"
