name: edirect_esearch
description: Perform searches against the NCBI databases
keywords:
  - NCBI
  - search
tools:
  - edirect:
      description: Entrez Direct (EDirect) is an advanced method for accessing the NCBI's set of interconnected databases (publication, sequence, structure, gene, variation, expression, etc.) from a UNIX terminal window. Functions take search terms from command-line arguments. Individual operations are combined to build multi-step queries. Record retrieval and formatting normally complete the process.
      homepage: https://eutils.ncbi.nlm.nih.gov/
      documentation: https://www.ncbi.nlm.nih.gov/books/NBK179288/
      licence: ['PUBLIC DOMAIN']

input:
  - query:
      type: string
      description: The search to be performed against the NCBI databases
  - db:
      type: string
      description: Which database to search

output:
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - xml:
      type: file
      description: NCBI search session saved to an XML file
      pattern: "*.xml"

authors:
  - "@MillironX"
